### ISSUE TITLE
API Policy

### ISSUE THREAD

**Issue by koxx12-dev** [NotEnoughUpdates/ursa-minor#4]
there is a small issue, 
![firefox_h7Aix93LTP](https://github.com/NotEnoughUpdates/ursa-minor/assets/80456351/f0493811-595e-4d91-8892-2903170711d5)
###### source: https://developer.hypixel.net/policies/

**Comment by lineargraph** [comment]
This is not an issue. We are not proxying to third party developers. We are proxying to ourselves. This proxy is only intended to be used by NEU (or by other mods, if they host their own instance).
